name: Deploy static content to Pages

on:
  push:
    branches: ['master']  # Use 'master' conforme sua configuração
  workflow_dispatch:  # Permite execução manual do workflow

permissions:
  contents: write  # Permite gravação no conteúdo do repositório
  pages: write     # Permite gravação no GitHub Pages
  id-token: write  # Permite a escrita do token de ID

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Atualizado para Node.js 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Prepare files for deployment
        run: |
          mkdir -p temp_dist
          cp -r dist/* temp_dist/
          ls temp_dist

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './temp_dist'  # Altera o caminho para a pasta temporária

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
