name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' # ou a versão que você estiver usando

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # ou o comando que você usa para build

      - name: Move files to deploy branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout deploy || git checkout --orphan deploy
          rm -rf ./*
          mv dist/* ./
          git add .
          git commit -m "Deploy: $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin deploy --force

